import Link from "next/link";
import type { Metadata } from "next";
export const metadata: Metadata = { title: "Privacy", description: "VarsityVue privacy, optional regional measurement and user choices." };
export default function PrivacyPage() {
  return <main className="mx-auto max-w-3xl px-5 py-12 text-white">
    <h1 className="text-3xl font-bold">Privacy at VarsityVue</h1>
    <p className="mt-4">This page explains optional Games Near Me measurement and related site processing. Regional collection is currently {process.env.NEXT_PUBLIC_COVERAGE_DEMAND_ENABLED === "true" ? "available only after an affirmative choice" : "off"}. The planned retention and monitoring described below must be installed and verified before collection starts.</p>
    <section id="regional-measurement" className="mt-8 space-y-4">
      <h2 className="text-xl font-bold">Optional regional measurement</h2>
      <p>If you allow regional measurement, VarsityVue can use approximate search geography and aggregate counts to decide where to expand football coverage. Declining does not limit Games Near Me. Your browser’s location permission is separate from this measurement choice; selecting a school center needs no location permission.</p>
      <p>Browser coordinates are requested only when you choose Use my location. They stay in page memory for discovery and are cleared on Clear, cancellation, relevant navigation or page departure. This feature does not put precise coordinates in persistent storage, cookies, navigation URLs or regional summaries. It does not track location continuously or infer geography from your IP address.</p>
      <p>An allowed summary uses an approximately 25-mile grid cell, the selected week, bounded result counts and control categories. Query text, selected schools or games, member identity and precise coordinates are excluded. Browser-location and school-center summaries remain separate: a chosen school center describes search geography, not where you live or stand. Reports use approximately 100-mile parent regions and suppress small counts. Counts represent accepted summaries, not unique people; suppression does not guarantee anonymity and repeated comparisons can reveal differences.</p>
      <h2 className="text-xl font-bold">Choice and withdrawal</h2>
      <p>The controls beside Games Near Me let you allow or stop measurement. Default is off. A versioned enabled/disabled preference is the only measurement item persisted in browser storage; it contains no identifier or interaction history. Older dormant choices do not authorize this version. If storage cannot be read, an explicit choice applies only to the mounted page; if storage remains readable but a write fails, the stored choice prevails conservatively.</p>
      <p>Withdrawal discards unfinished measurement and synchronizes across mounted tabs when browser storage events are available. Permission is checked again before delivery. Opting in starts with current controls and does not reconstruct earlier interactions. Requests already transmitted cannot be recalled. Nonidentifiable aggregate counts cannot be located for person-level deletion. Browser delivery is best effort and may fail.</p>
      <h2 className="text-xl font-bold">Planned retention</h2>
      <p>Before activation, daily maintenance and independent failure monitoring must be verified. Daily leaf aggregates are intended to keep 30 America/Chicago calendar dates including today. Older leaves are transactionally rolled into parent-only monthly and season totals and deleted at the next successful maintenance run. Proposed daily execution begins at 08:00 UTC, with recovery runs and a one-hour missed-run grace period; delayed or failed maintenance can extend retention and requires owner intervention.</p>
      <p>Monthly aggregates retain 13 calendar-month cohorts including the current month. Season aggregates expire February 1 of the second year after that season. These are separate aggregate copies. Deleting application records does not immediately remove historical provider backups, logs or exports; provider backup and restoration safeguards require separate verification.</p>
      <h2 className="text-xl font-bold">Providers and separate analytics</h2>
      <p>Vercel hosts the site and request endpoint; Supabase processes and stores database aggregates. Providers receive connection metadata such as IP address and user agent and process request contents in transit. The application excludes those metadata fields from regional tables, but we do not claim providers never retain them. Logging, diagnostics, request-body capture, session replay and backup settings must be checked before regional activation. A planned independent monitor receives empty operational signals, not regional summaries.</p>
      <p>Existing Vercel Web Analytics and site conversion analytics operate separately from this regional choice. Vercel documents processing visited URLs, referrers, browser/device details and approximate geography derived from connection information; custom site events can include contextual properties. Public search/filter URLs may contain search text, although this feature never puts precise location or measurement consent in them. Declining regional measurement does not turn off those existing analytics.</p>
      <p>Provider information: <a className="underline" href="https://vercel.com/docs/analytics/privacy-policy">Vercel analytics privacy</a> and <a className="underline" href="https://supabase.com/docs/guides/platform/backups">Supabase backups</a>. Actual project retention, diagnostics and replay settings are not established by these documents.</p>
      <p>Questions or withdrawal help: <a className="underline" href="mailto:info@varsityvue.com">info@varsityvue.com</a>. Contest-specific information is available in the <Link href="/pickem/privacy" className="underline">Pick ’Em privacy notice</Link>. This disclosure does not promise legal compliance or person-level removal from aggregates.</p>
    </section>
  </main>;
}
