import Link from "next/link";
import { redirect } from "next/navigation";

import { playerProfiles, type PlayerProfile } from "@/data/player-profiles";
import { getSchoolBySlug, getSchools } from "@/lib/schools";
import { createClient } from "@/lib/supabase/server";
import { addRosterPlayer, removeRosterPlayer } from "./actions";

type Props = { searchParams: Promise<{ school?: string; q?: string; player?: string; profile?: string; message?: string; updated?: string }> };
type RosterPlayer = { id: string; school_slug: string; first_name: string; last_name: string; jersey_number: number | null; position: string | null; grade: string | null; player_profile_id: string | null };
type Candidate = { key: string; source: "profile" | "managed"; sourceId: string; schoolSlug: string; firstName: string; lastName: string; jerseyNumber: number | null; position: string | null; grade: string | null; playerProfileId: string | null };

const norm = (value: string) => value.trim().toLowerCase();
function splitName(name: string) { const parts = name.trim().split(/\s+/); return { firstName: parts[0] ?? "", lastName: parts.slice(1).join(" ") }; }
function shortGrade(grade?: PlayerProfile["grade"] | null) { return grade === "Freshman" ? "Fr" : grade === "Sophomore" ? "So" : grade === "Junior" ? "Jr" : grade === "Senior" ? "Sr" : null; }
function fromProfile(player: PlayerProfile): Candidate { const name = splitName(player.name); const jersey = player.jerseyNumber === undefined ? null : Number(player.jerseyNumber); return { key: `profile:${player.playerId}`, source: "profile", sourceId: player.playerId, schoolSlug: player.schoolSlug, ...name, jerseyNumber: Number.isFinite(jersey) ? jersey : null, position: player.positions?.join(" / ") ?? null, grade: shortGrade(player.grade), playerProfileId: player.playerId }; }
function fromManaged(player: RosterPlayer): Candidate { return { key: `managed:${player.id}`, source: "managed", sourceId: player.id, schoolSlug: player.school_slug, firstName: player.first_name, lastName: player.last_name, jerseyNumber: player.jersey_number, position: player.position, grade: player.grade, playerProfileId: player.player_profile_id }; }
function samePlayer(a: Candidate, b: Candidate) { if (a.playerProfileId && b.playerProfileId) return a.schoolSlug === b.schoolSlug && a.playerProfileId === b.playerProfileId; const sameName = norm(`${a.firstName} ${a.lastName}`) === norm(`${b.firstName} ${b.lastName}`); return sameName && a.schoolSlug === b.schoolSlug && (a.jerseyNumber === null || b.jerseyNumber === null || a.jerseyNumber === b.jerseyNumber); }
function matches(player: Candidate, query: string) { return norm(`${player.firstName} ${player.lastName} ${player.jerseyNumber ?? ""} ${player.position ?? ""}`).includes(query); }

export default async function ManageRosterPage({ searchParams }: Props) {
  const params = await searchParams;
  const supabase = await createClient();
  const { data: claims } = await supabase.auth.getClaims();
  const userId = claims?.claims?.sub;
  if (!userId) redirect(`/login?next=${encodeURIComponent(params.school ? `/manage-roster?school=${params.school}` : "/manage-roster")}`);

  const [{ data: roles }, { data: assignments }] = await Promise.all([
    supabase.from("user_roles").select("role").eq("user_id", userId),
    supabase.from("contributor_school_assignments").select("school_slug").eq("user_id", userId).eq("assignment_role", "coach").eq("active", true),
  ]);
  const isAdmin = roles?.some((row) => row.role === "admin") ?? false;
  const coachSlugs = new Set((assignments ?? []).map((row) => row.school_slug));
  const schools = isAdmin ? getSchools().filter((school) => school.status !== "archived") : getSchools().filter((school) => coachSlugs.has(school.slug));
  if (!isAdmin && !schools.length) redirect("/account");

  const selectedSlug = params.school && schools.some((school) => school.slug === params.school) ? params.school : schools[0]?.slug;
  const school = selectedSlug ? getSchoolBySlug(selectedSlug) : undefined;
  const { data: rosterData } = selectedSlug ? await supabase.from("school_roster_players").select("id, school_slug, first_name, last_name, jersey_number, position, grade, player_profile_id").eq("school_slug", selectedSlug).eq("season", 2026).eq("active", true).order("jersey_number", { ascending: true, nullsFirst: false }).order("last_name", { ascending: true }) : { data: [] };
  const roster = (rosterData ?? []) as RosterPlayer[];

  const query = norm(params.q ?? "");
  let results: Candidate[] = [];
  if (query.length >= 2 && selectedSlug) {
    const { data } = await supabase.from("school_roster_players").select("id, school_slug, first_name, last_name, jersey_number, position, grade, player_profile_id").eq("school_slug", selectedSlug).eq("season", 2026).eq("active", true).limit(500);
    const combined = [...playerProfiles.filter((p) => p.season === 2026 && p.schoolSlug === selectedSlug).map(fromProfile), ...((data ?? []) as RosterPlayer[]).map(fromManaged)];
    for (const candidate of combined) if (matches(candidate, query) && !results.some((existing) => samePlayer(existing, candidate))) results.push(candidate);
    results = results.sort((a, b) => (a.source === "profile" ? 0 : 1) - (b.source === "profile" ? 0 : 1) || `${a.lastName} ${a.firstName}`.localeCompare(`${b.lastName} ${b.firstName}`)).slice(0, 10);
  }

  let selected: Candidate | null = null;
  if (params.profile && selectedSlug) { const profile = playerProfiles.find((p) => p.playerId === params.profile && p.season === 2026 && p.schoolSlug === selectedSlug); selected = profile ? fromProfile(profile) : null; }
  else if (params.player && selectedSlug) { const { data } = await supabase.from("school_roster_players").select("id, school_slug, first_name, last_name, jersey_number, position, grade, player_profile_id").eq("id", params.player).eq("school_slug", selectedSlug).eq("season", 2026).eq("active", true).maybeSingle(); selected = data ? fromManaged(data as RosterPlayer) : null; }

  const current = roster.map(fromManaged);
  const onRoster = (candidate: Candidate) => current.some((entry) => samePlayer(entry, candidate));

  return <main className="min-h-screen bg-[var(--vv-bg)] px-4 py-8 text-white sm:px-6 sm:py-12 lg:px-8"><div className="mx-auto max-w-5xl">
    <div className="flex items-center justify-between gap-4"><Link href="/account" className="text-xs font-black uppercase tracking-[0.12em] text-white/45 hover:text-white">← Account</Link><span className="rounded-full border border-white/10 bg-white/[0.05] px-3 py-1 text-[9px] font-black uppercase tracking-[0.12em] text-white/45">2026 Roster</span></div>
    <section className="mt-4 rounded-[1.5rem] border border-white/10 bg-[radial-gradient(circle_at_top_left,rgba(122,16,34,0.35),transparent_42%),rgba(255,255,255,0.04)] p-5 shadow-2xl sm:p-7"><p className="text-[10px] font-black uppercase tracking-[0.2em] text-[var(--vv-accent)]">Team Management</p><h1 className="mt-2 text-3xl font-black sm:text-5xl">Manage Roster</h1><p className="mt-3 text-sm text-white/55 sm:text-base">{isAdmin ? "Manage 2026 rosters for any active VarsityVue program." : "Manage the 2026 roster for programs where you are assigned as a coach."}</p></section>
    {params.message && <div className="mt-4 rounded-xl border border-amber-300/20 bg-amber-300/10 px-4 py-3 text-sm text-amber-100">{params.message}</div>}{params.updated && <div className="mt-4 rounded-xl border border-emerald-300/20 bg-emerald-300/10 px-4 py-3 text-sm text-emerald-100">Roster updated.</div>}
    <section className="mt-5 rounded-[1.35rem] border border-white/10 bg-white/[0.04] p-4 sm:p-6"><p className="mb-3 text-[10px] font-black uppercase tracking-[0.18em] text-white/35">Select program</p><div className="flex flex-wrap gap-2">{schools.map((s) => <Link key={s.slug} href={`/manage-roster?school=${encodeURIComponent(s.slug)}`} className={`rounded-full border px-3 py-2 text-xs font-black ${s.slug === selectedSlug ? "border-[var(--vv-primary)] bg-[var(--vv-primary)]" : "border-white/10 bg-black/20 text-white/60"}`}>{s.name}</Link>)}</div></section>
    {school && <>
      <section className="mt-5 rounded-[1.35rem] border border-white/10 bg-white/[0.04] p-4 sm:p-6"><div className="flex items-end justify-between gap-3"><div><p className="text-[10px] font-black uppercase tracking-[0.18em] text-white/35">Player Search</p><h2 className="mt-1 text-xl font-black">Find an existing player</h2><p className="mt-1 text-xs text-white/40">Search existing 2026 players for {school.name}. Verified profiles are identified in the results.</p></div>{query && <Link href={`/manage-roster?school=${encodeURIComponent(school.slug)}`} className="text-xs font-black text-white/45">Clear</Link>}</div>
        <form method="get" className="mt-4 flex gap-2"><input type="hidden" name="school" value={school.slug}/><input type="search" name="q" defaultValue={params.q ?? ""} minLength={2} placeholder="Search name, jersey, or position" className="min-w-0 flex-1 rounded-xl border border-white/10 bg-black/35 px-3 py-2.5 text-sm outline-none"/><button className="rounded-xl bg-white/10 px-4 py-2.5 text-xs font-black">Search</button></form>
        {query.length > 0 && query.length < 2 && <p className="mt-3 text-xs text-amber-100/70">Enter at least 2 characters to search players.</p>}
        {query.length >= 2 && <div className="mt-4 overflow-hidden rounded-xl border border-white/10 bg-black/25">{results.length ? results.map((p) => { const present = onRoster(p); const key = p.source === "profile" ? `profile=${encodeURIComponent(p.sourceId)}` : `player=${encodeURIComponent(p.sourceId)}`; return <div key={p.key} className="flex items-center gap-3 border-b border-white/10 px-3 py-3 last:border-0"><div className="flex h-9 w-9 items-center justify-center rounded-lg border border-white/10 bg-white/[0.05] text-xs font-black">{p.jerseyNumber ?? "—"}</div><div className="min-w-0 flex-1"><p className="truncate text-sm font-black">{p.firstName} {p.lastName} {p.playerProfileId && <span className="ml-1 rounded-full border border-sky-300/15 bg-sky-300/10 px-1.5 py-0.5 text-[8px] uppercase text-sky-100/80">Verified</span>}</p><p className="truncate text-[10px] uppercase text-white/35">{school.name}{p.position ? ` · ${p.position}` : ""}{p.grade ? ` · ${p.grade}` : ""}</p></div>{present ? <span className="text-[9px] font-black uppercase text-emerald-200/70">On roster</span> : <Link href={`/manage-roster?school=${encodeURIComponent(school.slug)}&q=${encodeURIComponent(params.q ?? "")}&${key}`} className="rounded-full border border-white/15 px-3 py-1.5 text-[9px] font-black uppercase">Select</Link>}</div> }) : <p className="p-4 text-sm text-white/45">No matching players found for {school.name}. You can create a new roster entry below.</p>}</div>}
      </section>
      <div className="mt-5 grid gap-5 lg:grid-cols-[1fr_0.8fr]">
        <section className="rounded-[1.35rem] border border-white/10 bg-white/[0.04] p-4 sm:p-6"><div className="flex items-end justify-between gap-3"><div><p className="text-[10px] font-black uppercase tracking-[0.18em] text-white/35">Current Roster</p><h2 className="mt-1 text-2xl font-black">{school.name}</h2></div><span className="text-xs font-black text-white/35">{roster.length} {roster.length === 1 ? "player" : "players"}</span></div><div className="mt-4 overflow-hidden rounded-xl border border-white/10 bg-black/25">{roster.length ? roster.map((p) => <div key={p.id} className="flex flex-wrap items-center gap-3 border-b border-white/10 px-3 py-3 last:border-0 sm:flex-nowrap"><div className="flex h-9 w-9 shrink-0 items-center justify-center rounded-lg border border-white/10 bg-white/[0.05] text-xs font-black">{p.jersey_number ?? "—"}</div><div className="min-w-0 flex-1"><p className="truncate text-sm font-black">{p.first_name} {p.last_name} {p.player_profile_id && <span className="ml-1 rounded-full border border-sky-300/15 bg-sky-300/10 px-1.5 py-0.5 text-[8px] uppercase text-sky-100/80">Verified</span>}</p><p className="text-[10px] font-bold uppercase text-white/35">{[p.position,p.grade].filter(Boolean).join(" · ") || "Details pending"}</p></div><div className="flex w-full items-center gap-2 pl-12 sm:w-auto sm:shrink-0 sm:pl-0"><Link href={`/manage-roster/edit/${p.id}`} className="flex-1 rounded-full border border-white/15 px-3 py-2 text-center text-[9px] font-black uppercase text-white/70 hover:bg-white/10 sm:flex-none sm:py-1.5">Edit</Link><form action={removeRosterPlayer} className="flex-1 sm:flex-none"><input type="hidden" name="school_slug" value={school.slug}/><input type="hidden" name="player_id" value={p.id}/><button type="submit" className="w-full rounded-full border border-red-300/15 px-3 py-2 text-[9px] font-black uppercase text-red-100/65 sm:py-1.5">Remove</button></form></div></div>) : <p className="p-4 text-sm text-white/45">No players have been added to this 2026 roster yet.</p>}</div></section>
        <section className="rounded-[1.35rem] border border-white/10 bg-white/[0.04] p-4 sm:p-6"><div className="flex items-start justify-between gap-3"><div><p className="text-[10px] font-black uppercase tracking-[0.18em] text-white/35">Add Player</p><h2 className="mt-1 text-xl font-black">{selected ? "Review player details" : "New roster entry"}</h2></div>{selected && <Link href={`/manage-roster?school=${encodeURIComponent(school.slug)}${params.q ? `&q=${encodeURIComponent(params.q)}` : ""}`} className="text-[9px] font-black uppercase text-white/40">Reset</Link>}</div><p className="mt-2 text-xs text-white/40">{selected ? `Review the details before adding this player to ${school.name}.` : "Search first to avoid duplicates, or enter a player who is not already in VarsityVue."}</p>{selected?.playerProfileId && <div className="mt-4 rounded-xl border border-sky-300/15 bg-sky-300/[0.08] px-3 py-2.5"><p className="text-[9px] font-black uppercase tracking-[0.12em] text-sky-100/80">Verified player profile</p><p className="mt-1 text-xs text-white/50">This roster entry will stay connected to the existing VarsityVue player identity. The verified name is locked.</p></div>}<form action={addRosterPlayer} className="mt-4 space-y-3"><input type="hidden" name="school_slug" value={school.slug}/>{selected?.playerProfileId && <input type="hidden" name="player_profile_id" value={selected.playerProfileId}/>}<div className="grid grid-cols-1 gap-3 sm:grid-cols-2"><Field label="First name" name="first_name" required defaultValue={selected?.firstName} disabled={Boolean(selected?.playerProfileId)}/><Field label="Last name" name="last_name" required defaultValue={selected?.lastName} disabled={Boolean(selected?.playerProfileId)}/></div><div className="grid grid-cols-1 gap-3 sm:grid-cols-2"><Field label="Jersey #" name="jersey_number" type="number" min="0" max="99" defaultValue={selected?.jerseyNumber ?? undefined}/><Field label="Position" name="position" placeholder="QB, WR, LB..." defaultValue={selected?.position ?? undefined}/></div><label className="block"><span className="text-[9px] font-black uppercase tracking-[0.12em] text-white/35">Grade</span><select name="grade" defaultValue={selected?.grade ?? ""} className="mt-1.5 w-full rounded-xl border border-white/10 bg-black/40 px-3 py-2.5 text-sm outline-none"><option value="">Unknown</option><option value="Fr">Freshman</option><option value="So">Sophomore</option><option value="Jr">Junior</option><option value="Sr">Senior</option></select></label><button type="submit" className="w-full rounded-xl bg-[var(--vv-primary)] px-4 py-3 text-sm font-black hover:bg-[#93142a]">{selected ? "Add to Roster" : "Add Player"}</button></form></section>
      </div>
    </>}
  </div></main>;
}

function Field({ label, name, type = "text", required = false, min, max, placeholder, defaultValue, disabled = false }: { label: string; name: string; type?: string; required?: boolean; min?: string; max?: string; placeholder?: string; defaultValue?: string | number; disabled?: boolean }) { return <label className="block"><span className="text-[9px] font-black uppercase tracking-[0.12em] text-white/35">{label}</span><input name={name} type={type} required={required} min={min} max={max} placeholder={placeholder} defaultValue={defaultValue} disabled={disabled} className={`mt-1.5 w-full rounded-xl border border-white/10 px-3 py-2.5 text-sm outline-none placeholder:text-white/20 ${disabled ? "cursor-not-allowed bg-white/[0.04] text-white/45" : "bg-black/40"}`}/></label>; }
