import nodeTest from 'node:test';
import {AsyncLocalStorage} from 'node:async_hooks';
import assert from 'node:assert/strict';
const testObservations=new AsyncLocalStorage();
const originalThrows=assert.throws.bind(assert),originalRejects=assert.rejects.bind(assert);
assert.throws=(fn,...args)=>originalThrows(()=>{try{return fn();}catch(e){testObservations.getStore()?.push(e.outcome??'VERIFICATION FAIL');throw e;}},...args);
assert.rejects=(fn,...args)=>originalRejects(async()=>{try{return await(typeof fn==='function'?fn():fn);}catch(e){testObservations.getStore()?.push(e.outcome??'VERIFICATION FAIL');throw e;}},...args);
const test=(name,body)=>nodeTest(name,async t=>testObservations.run([],async()=>{await body(t);t.diagnostic(JSON.stringify({id:name.split(' expected=')[0],expected:name.split(' expected=')[1]??'non-PASS',assertions:'PASS',observedErrorClasses:testObservations.getStore(),syntheticOnly:true}));}));

import {readFileSync} from 'node:fs';
import {generateKeyPairSync,sign} from 'node:crypto';
import {deflateRawSync} from 'node:zlib';
import {createRequire} from 'node:module';
import {parseCanonical,bytes} from './run-trusted-runtime.mjs';
import {readZip,githubReader,validateOidc,requestAttestation} from './verify-safe-ci-evidence.mjs';
const policy=parseCanonical(readFileSync(new URL('./trusted-runtime-policy.json',import.meta.url)));
function crc32(b){let c=0xffffffff;for(const byte of b){c^=byte;for(let i=0;i<8;i++)c=(c>>>1)^((c&1)?0xedb88320:0);}return(c^0xffffffff)>>>0;}
function zip(entries){const locals=[],centrals=[];let offset=0;for(const e of entries){const name=Buffer.from(e.path),content=e.bytes??Buffer.from('synthetic'),raw=e.deflate?deflateRawSync(content):content,method=e.deflate?8:0,l=Buffer.alloc(30),c=Buffer.alloc(46);l.writeUInt32LE(0x04034b50);l.writeUInt16LE(20,4);l.writeUInt16LE(method,8);l.writeUInt32LE(crc32(content),14);l.writeUInt32LE(raw.length,18);l.writeUInt32LE(content.length,22);l.writeUInt16LE(name.length,26);c.writeUInt32LE(0x02014b50);c.writeUInt16LE(3<<8|20,4);c.writeUInt16LE(20,6);c.writeUInt16LE(method,10);c.writeUInt32LE(crc32(content),16);c.writeUInt32LE(raw.length,20);c.writeUInt32LE(content.length,24);c.writeUInt16LE(name.length,28);c.writeUInt32LE((e.mode??0o100644)*65536>>>0,38);c.writeUInt32LE(offset,42);locals.push(l,name,raw);centrals.push(c,name);offset+=30+name.length+raw.length;}const central=Buffer.concat(centrals),end=Buffer.alloc(22);end.writeUInt32LE(0x06054b50);end.writeUInt16LE(entries.length,8);end.writeUInt16LE(entries.length,10);end.writeUInt32LE(central.length,12);end.writeUInt32LE(offset,16);return Buffer.concat([...locals,central,end]);}
for(const deflate of [false,true])test('Z001 ZIP '+deflate+' expected=PASS SYNTHETIC ONLY',()=>assert.equal(readZip(zip([{path:'envelope.json',deflate}]),policy.limits)[0].bytes.toString(),'synthetic'));
for(const [id,entries] of [['Z002',[{path:'../x'}]],['Z003',[{path:'/x'}]],['Z004',[{path:'x'},{path:'x'}]],['Z005',[{path:'x',mode:0o120777}]],['Z006',[{path:'x',mode:0o020600}]]])test(id+' unsafe ZIP expected=VERIFICATION FAIL',()=>assert.throws(()=>readZip(zip(entries),policy.limits)));
for(const [id,mutate] of [['Z007',b=>{b[0]=0;}],['Z008',b=>{b[35]^=1;}],['Z009',b=>{b.writeUInt32LE(999999999,22);}],['Z010',b=>b.writeUInt16LE(8,6)],['Z011',b=>b.writeUInt16LE(1,b.length-2)]])test(id+' malformed ZIP expected=VERIFICATION FAIL',()=>{const b=zip([{path:'x'}]);mutate(b);assert.throws(()=>readZip(b,policy.limits));});
test('Z012 oversized expansion expected=VERIFICATION FAIL',()=>assert.throws(()=>readZip(zip([{path:'x',bytes:Buffer.alloc(10000),deflate:true}]),{...policy.limits,maxMemberBytes:10})));
test('Z013 trailing ZIP expected=VERIFICATION FAIL',()=>assert.throws(()=>readZip(Buffer.concat([zip([{path:'x'}]),Buffer.from('extra')]),policy.limits)));
test('P001 all API pages expected=PASS SYNTHETIC ONLY',async()=>{let count=0;const api=githubReader('TEST-ONLY',async(url,options)=>{assert.equal(new URL(url).origin,'https://api.github.com');assert.equal(options.redirect,'error');return new Response(JSON.stringify({runs:[++count]}),{headers:count===1?{link:'<https://api.github.com/page2>; rel="next"'}:{}});});assert.deepEqual(await api.pages('https://api.github.com/page1','runs'),{items:[1,2],pagesComplete:true});});
for(const [id,reply] of [['P002',()=>new Response('rate limit',{status:429})],['P003',()=>new Response('{')],['P004',()=>new Response('{}')],['P005',()=>new Response('{"runs":[]}',{headers:{link:'<https://evil.invalid/x>; rel="next"'}})],['P006',()=>new Response('{"runs":[]}',{headers:{link:'<https://api.github.com/page1>; rel="next"'}})]])test(id+' API fail closed expected=non-PASS',async()=>{await assert.rejects(githubReader('TEST-ONLY',async()=>reply()).pages('https://api.github.com/page1','runs'));});
const rsa=generateKeyPairSync('rsa',{modulusLength:2048});const jwk={...rsa.publicKey.export({format:'jwk'}),kid:'TEST-ONLY'};const claims={iss:'https://token.actions.githubusercontent.com',aud:'varsityvue-trusted-runtime',repository:'varsityvue/varsityvue-site',repository_id:'1115452404',workflow_ref:'varsityvue/varsityvue-site/.github/workflows/varsityvue-safe-required.yml@refs/heads/main',ref:'refs/pull/123/merge',run_id:'2',run_attempt:'1',iat:990,nbf:990,exp:1100};
function jwt(c=claims){const h=Buffer.from(JSON.stringify({alg:'RS256',kid:jwk.kid})).toString('base64url'),p=Buffer.from(JSON.stringify(c)).toString('base64url');return h+'.'+p+'.'+sign('RSA-SHA256',Buffer.from(h+'.'+p),rsa.privateKey).toString('base64url');}
test('O001 real crypto synthetic OIDC expected=PASS SYNTHETIC ONLY',()=>assert.equal(validateOidc(jwt(),jwk,claims,1000).repository,claims.repository));
for(const k of ['repository','repository_id','workflow_ref','ref','run_id','run_attempt','aud','iss'])test('O-'+k+' wrong claim expected=BLOCKED — AUTHENTICATION',()=>assert.throws(()=>validateOidc(jwt({...claims,[k]:'wrong'}),jwk,claims,1000),e=>e.outcome==='BLOCKED — AUTHENTICATION'));
test('O002 invalid OIDC signature expected=BLOCKED — AUTHENTICATION',()=>assert.throws(()=>validateOidc(jwt().split('.').slice(0,2).join('.')+'.'+Buffer.alloc(256).toString('base64url'),jwk,claims,1000)));
test('O003 stale OIDC expected=BLOCKED — AUTHENTICATION',()=>assert.throws(()=>validateOidc(jwt(),jwk,claims,1200)));
test('O004 no candidate auth overlap expected=BLOCKED — AUTHENTICATION',async()=>assert.rejects(requestAttestation({candidateTerminated:false,collectorSealed:true,policy}),e=>e.outcome==='BLOCKED — AUTHENTICATION'));
test('W001 workflow isolation permissions and unique final gate expected=PASS',()=>{
 const {load}=createRequire(import.meta.url)('js-yaml');const w=load(readFileSync(new URL('../.github/workflows/varsityvue-safe-required.yml',import.meta.url),'utf8'));assert.deepEqual(w.permissions,{});assert.equal(w.jobs['safe-verification'].if,'${{ always() }}');assert.deepEqual(w.jobs['safe-verification'].needs,['readiness','runtime','attestation']);assert.equal(Object.values(w.jobs).filter(j=>j.name==='VarsityVue safe verification').length,1);assert.deepEqual(w.jobs.runtime.permissions,{});assert.deepEqual(w.jobs.runtime['runs-on'],['self-hosted','linux','varsityvue-ephemeral-default-deny-v1']);for(const [id,j]of Object.entries(w.jobs)){assert.equal(j['continue-on-error'],undefined);assert.equal(j.permissions?.['id-token'],id==='attestation'?'write':undefined);for(const s of j.steps){assert.equal(s['continue-on-error'],undefined);if(s.uses?.startsWith('actions/checkout')){assert.equal(s.with['persist-credentials'],false);assert.equal(s.with.ref,'${{ github.event.pull_request.base.sha }}');}}}assert.deepEqual(Object.keys(w.on),['pull_request']);assert.equal(w.on.pull_request.paths,undefined);
});
test('P007 token-free archive redirect expected=PASS SYNTHETIC ONLY',async()=>{const b=zip([{path:'x'}]);const {hash}=await import('./run-trusted-runtime.mjs');let calls=0;const api=githubReader('TEST-ONLY',async(url,options)=>{calls++;if(calls===1)return new Response(null,{status:302,headers:{location:'https://fixture.blob.core.windows.net/archive'}});assert.equal(options.headers,undefined);assert.equal(options.redirect,'error');return new Response(b);});assert.equal((await api.archive('https://api.github.com/archive',hash(b),policy.limits)).length,1);assert.equal(calls,2);});
test('P008 forbidden archive redirect expected=VERIFICATION FAIL',async()=>await assert.rejects(githubReader('TEST-ONLY',async()=>new Response(null,{status:302,headers:{location:'https://evil.invalid/archive'}})).archive('https://api.github.com/archive','a'.repeat(64),policy.limits)));
test('P009 wrong archive hash expected=VERIFICATION FAIL',async()=>await assert.rejects(githubReader('TEST-ONLY',async()=>new Response(zip([{path:'x'}]))).archive('https://api.github.com/archive','a'.repeat(64),policy.limits)));
test('O005 OIDC only requested after seal expected=PASS SYNTHETIC ONLY',async()=>{let calls=0;const p=structuredClone(policy);p.attestation.endpoint='https://attestation.example.invalid/v1/attest';p.attestation.publicKey='TEST-ONLY';const result=await requestAttestation({binding:{runId:1},manifestDigest:'a'.repeat(64),candidateTerminated:true,collectorSealed:true,policy:p,requestUrl:'https://pipelines.actions.githubusercontent.com/token',requestToken:'TEST-ONLY-REQUEST',fetcher:async(url,options)=>{calls++;if(calls===1){assert.equal(options.headers.Authorization,'Bearer TEST-ONLY-REQUEST');return new Response('{"value":"TEST-ONLY-OIDC"}');}assert.equal(new URL(url).origin,'https://attestation.example.invalid');assert.equal(options.headers.Authorization,'Bearer TEST-ONLY-OIDC');return new Response(bytes({synthetic:true}));}});assert.deepEqual(result,{synthetic:true});assert.equal(calls,2);});
test('O006 wrong OIDC request host expected=BLOCKED — AUTHENTICATION',async()=>{const p=structuredClone(policy);p.attestation.endpoint='https://service.invalid';p.attestation.publicKey='TEST-ONLY';await assert.rejects(requestAttestation({candidateTerminated:true,collectorSealed:true,policy:p,requestUrl:'https://evil.invalid/token',fetcher:()=>assert.fail('must not fetch')}),e=>e.outcome==='BLOCKED — AUTHENTICATION');});
test('O007 missing expected OIDC authority expected=BLOCKED — AUTHENTICATION',()=>assert.throws(()=>validateOidc(jwt(),jwk,{},1000),e=>e.outcome==='BLOCKED — AUTHENTICATION'));
test('P010 complete live tree/tool/merge snapshot expected=PASS SYNTHETIC ONLY',async()=>{
 const {platformSnapshot}=await import('./verify-safe-ci-evidence.mjs');const h='a'.repeat(40),b={repository:'varsityvue/varsityvue-site',pr:1,head:h,base:h,headTree:h,baseTree:h,bootstrap:h,bootstrapTree:h,merge:h,mergeParents:[h,h],workflowPath:'.github/workflows/varsityvue-safe-required.yml',toolBlobs:{'scripts/tool.mjs':h,'.github/workflows/varsityvue-safe-required.yml':h}};const reader={async json(url){if(url.includes('/pulls/'))return {number:1,head:{sha:h},base:{sha:h,ref:'main'}};if(url.includes('/git/ref/'))return {object:{sha:h}};if(url.includes('/git/trees/'))return {truncated:false,tree:[{path:'scripts/tool.mjs',sha:h,type:'blob',mode:'100644'},{path:'.github/workflows/varsityvue-safe-required.yml',sha:h,type:'blob',mode:'100644'}]};return {sha:h,tree:{sha:h},parents:[{sha:h},{sha:h}]};}};assert.deepEqual(await platformSnapshot(reader,b),b);
 for(const mutation of ['tree','tool','merge','pr']){const bad={async json(url){const data=await reader.json(url);if(mutation==='tree'&&url.includes('/git/commits/'))data.tree.sha='b'.repeat(40);if(mutation==='tool'&&url.includes('/git/trees/'))data.tree[0].sha='b'.repeat(40);if(mutation==='merge'&&url.includes('/git/commits/'))data.parents.reverse().pop();if(mutation==='pr'&&url.includes('/pulls/'))data.head.sha='b'.repeat(40);return data;}};await assert.rejects(platformSnapshot(bad,b));}
});
test('W002 every required producer conclusion fails closed expected=PASS SYNTHETIC ONLY',()=>{
 const {load}=createRequire(import.meta.url)('js-yaml'),w=load(readFileSync(new URL('../.github/workflows/varsityvue-safe-required.yml',import.meta.url),'utf8'));const step=w.jobs['safe-verification'].steps[0];for(const variable of ['READINESS','RUNTIME','ATTESTATION'])assert.ok(step.run.includes('test "$'+variable+'" = success'));for(const nonpass of ['skipped','cancelled','neutral','timed_out','action_required','missing','stale','expired','malformed'])assert.notEqual(nonpass,'success');assert.equal(policy.activation,false);assert.equal(policy.runner.publicKey,null);assert.equal(policy.attestation.publicKey,null);
});
