'use client';
import { useState } from 'react';
import Image from 'next/image';
import { useRouter } from 'next/navigation';
import type { IngestionDraft } from '@/lib/ingestion-contracts';
import type { Submission } from '@/lib/ingestion-persistence';
import { saveSubmission,decideSubmission,deleteSource } from '@/app/internal/data-ingestion/actions';
import { getPlayerId } from '@/lib/player-identity';

type Catalog={schools:{slug:string;name:string}[];games:{id:string;season:number;homeSchoolSlug?:string;awaySchoolSlug?:string;homeTeam?:string;awayTeam?:string}[];players:{playerId:string;schoolSlug:string;season:number;name:string}[];managed:{internalId:string;schoolSlug:string;season:number;name:string;active:boolean;publicPlayerId?:string}[]};
const label=(key:string)=>key.replace(/([A-Z])/g,' $1').replace(/^./,c=>c.toUpperCase());
const style='w-full rounded border border-white/25 bg-black p-2 text-white';
const button='rounded border border-white/30 px-3 py-2 hover:bg-white/10 disabled:opacity-40';
export default function IngestionReview({submission,catalog}:{submission:Submission;catalog:Catalog}) {
 const router=useRouter();const [draft,setDraft]=useState<IngestionDraft|null>(submission.current?.draft??null);
 const [message,setMessage]=useState('');const [busy,setBusy]=useState(false);const [dirty,setDirty]=useState(false);const [reason,setReason]=useState('');
 const run=async(action:()=>Promise<unknown>)=>{setBusy(true);setMessage('');try{await action();setDirty(false);router.refresh();setMessage('Saved. Reloading current revision.');}catch(e){setMessage(e instanceof Error?e.message:'Operation failed.');}finally{setBusy(false);}};
 const edit=(path:(string|number)[],value:unknown,remove=false)=>{if(!draft)return;const next=structuredClone(draft);let item:Record<string,unknown>=next as unknown as Record<string,unknown>;for(const k of path.slice(0,-1))item=item[k] as Record<string,unknown>;const key=path[path.length-1];if(remove)delete item[key];else item[key]=value;setDraft(next);setDirty(true);};
 const scopedGames=catalog.games.filter(g=>g.season===submission.season&&[g.homeSchoolSlug,g.awaySchoolSlug].includes(submission.school_slug));
 const scopedPlayers=catalog.players.filter(p=>p.season===submission.season&&p.schoolSlug===submission.school_slug);
 function editor(value:unknown,path:(string|number)[],name:string):React.ReactNode {
  if(name==='completeness'&&value===undefined)value=[];
  if(name==='quarters'&&Array.isArray(value))return <label key={path.join('.')} className="block">Quarter scores (comma separated; empty means no supplied quarters)<input aria-label="Quarter scores" className={style} value={value.join(', ')} onChange={e=>edit(path,e.target.value.trim()?e.target.value.split(',').map(n=>Number(n.trim())):[])}/></label>;
  if(Array.isArray(value))return <fieldset className="space-y-3 border border-white/20 p-3" key={path.join('.')}><legend>{label(name)}</legend>{value.map((row,i)=><div className="space-y-2 border-b border-white/20 pb-3" key={i}>{editor(row,[...path,i],`${name} ${i+1}`)}<button type="button" className={button} onClick={()=>edit(path,value.filter((_,n)=>n!==i))}>Remove row {i+1}</button></div>)}{['rows','teamStats','rushing','passing','receiving','quarterScores','scoringPlays','completeness'].includes(name)&&<button type="button" className={button} onClick={()=>{
   const schoolSlug=submission.school_slug;const omitted={state:'omitted'};let row:unknown;
   if(name==='rows')row=submission.data_class==='roster'?{rowId:crypto.randomUUID(),name:'',player:{state:'unresolved',candidates:[]},jerseyNumber:omitted,grade:omitted,positions:omitted,height:omitted,weight:omitted}:{rowId:crypto.randomUUID(),game:{state:'unresolved',candidates:[]},opponent:{state:'unresolved',candidates:[]},week:omitted,date:omitted,kickoffTime:omitted,timeZone:{state:'known',value:'America/Chicago'},site:omitted,location:omitted};
   else row=name==='teamStats'?{schoolSlug}:name==='completeness'?{schoolSlug,categories:{quarterScoring:{status:'unknown'},scoringPlays:{status:'unknown'},teamStats:{status:'unknown'},rushing:{status:'unknown'},passing:{status:'unknown'},receiving:{status:'unknown'}}}:name==='quarterScores'?{schoolSlug,quarters:[],total:undefined}:name==='scoringPlays'?{schoolSlug,quarter:1,description:''}:{schoolSlug,player:'',...(name==='receiving'?{receptions:undefined,yards:undefined}:name==='passing'?{completions:undefined,attempts:undefined,yards:undefined}:{attempts:undefined,yards:undefined})};
   edit(path,[...value,row]);
  }}>Add {label(name)} row</button>}</fieldset>;
  if(value&&typeof value==='object') {
   const obj=value as Record<string,unknown>;
   if('state' in obj&&['known','unknown','omitted','unavailable'].includes(String(obj.state))) return <label className="block" key={path.join('.')}><span>{label(name)}</span><select aria-label={`${label(name)} availability`} className={style} value={String(obj.state)} onChange={e=>edit(path,e.target.value==='known'?{state:'known',value:name==='week'||name==='weight'?undefined:name==='positions'?[]:''}:{state:e.target.value})}><option value="known">Provided</option><option value="unknown">Unknown</option><option value="omitted">Not provided</option><option value="unavailable">Unavailable</option></select>{obj.state==='known'&&(name==='site'||name==='grade'?<select className={style} aria-label={label(name)} value={String(obj.value??'')} onChange={e=>edit([...path,'value'],e.target.value)}><option value="">Choose</option>{(name==='site'?['home','away','neutral']:['Freshman','Sophomore','Junior','Senior']).map(s=><option key={s}>{s}</option>)}</select>:<input className={style} aria-label={label(name)} type={name==='date'?'date':name==='kickoffTime'?'time':name==='week'||name==='weight'?'number':'text'} value={Array.isArray(obj.value)?obj.value.join(', '):String(obj.value??'')} onChange={e=>edit([...path,'value'],name==='week'||name==='weight'?e.target.value===''?undefined:Number(e.target.value):name==='positions'?e.target.value.split(',').map(s=>s.trim()).filter(Boolean):e.target.value)}/>)}</label>;
   if('state' in obj) {
    const rowPath=path.slice(0,-1);let row:unknown=draft;for(const p of rowPath)row=(row as Record<string,unknown>)[p];const rowObj=row as Record<string,unknown>;
    const options=name==='opponent'?catalog.schools.filter(s=>s.slug!==submission.school_slug).map(s=>({id:s.slug,label:s.name})):name==='player'?scopedPlayers.map(p=>({id:`public:${p.playerId}`,label:p.name})):scopedGames.map(g=>({id:g.id,label:`${g.awayTeam??g.awaySchoolSlug} at ${g.homeTeam??g.homeSchoolSlug}`}));
    if(name==='player')options.push(...catalog.managed.filter(p=>p.active&&p.schoolSlug===submission.school_slug&&p.season===submission.season&&(!scopedPlayers.some(s=>s.playerId===p.publicPlayerId)||obj.id===`managed:${p.internalId}`)).map(p=>({id:`managed:${p.internalId}`,label:`Managed roster: ${p.name}`})));
    if(name==='player'&&typeof rowObj.name==='string')options.push({id:`new:${getPlayerId(submission.school_slug,rowObj.name,submission.season)}`,label:'Explicitly accept a new distinct provisional identity'});
    if(name==='game'&&submission.operation==='create') options.push({id:`new:${String(rowObj.rowId)}`,label:'Explicitly confirm new schedule candidate'});
    return <label className="block" key={path.join('.')}><span>{label(name)} — explicit identity confirmation</span><select className={style} aria-label={label(name)} value={obj.state==='confirmed'?String(obj.id):''} onChange={e=>edit(path,e.target.value?{state:'confirmed',id:e.target.value,confirmedBy:'server'}:{state:'unresolved',candidates:[]})}><option value="">Unresolved — choose explicitly</option>{options.map(o=><option key={o.id} value={o.id}>{o.label} ({o.id})</option>)}</select></label>;
   }
   let keys=Object.keys(obj).filter(k=>!['rowId','confirmedBy'].includes(k));
   if('quarterScores' in obj&&!keys.includes('completeness'))keys.push('completeness');
   if('status' in obj&&!keys.includes('note'))keys.push('note');
   if(String(path[path.length-2])==='scoringPlays'&&!keys.includes('clock'))keys.push('clock');
   if(['rushing','passing','receiving','teamStats'].includes(String(path[path.length-2]))) {
    const category=String(path[path.length-2]);const extras=category==='teamStats'?['firstDowns','rushingAttempts','rushingYards','passingYards','totalYards','completions','passAttempts','interceptionsThrown','punts','puntAverage','fumbles','fumblesLost','penalties','penaltyYards']:category==='passing'?['playerId','completions','attempts','yards','touchdowns','interceptions']:category==='receiving'?['playerId','receptions','yards','touchdowns']:['playerId','attempts','yards','touchdowns'];
    keys=[...new Set([...keys,...extras])];
   }
   return <div className={'rows' in obj?'space-y-3':'grid gap-3 sm:grid-cols-2'} key={path.join('.')}>{keys.map(k=>editor(obj[k],[...path,k],k))}</div>;
  }
  if(name==='schoolSlug')return <label key={path.join('.')}><span>School</span><select className={style} value={String(value??'')} aria-label="Row school" onChange={e=>edit(path,e.target.value)}>{catalog.schools.map(s=><option value={s.slug} key={s.slug}>{s.name}</option>)}</select></label>;
  if(name==='playerId')return <label key={path.join('.')}><span>Existing player identity (no automatic match)</span><select className={style} value={String(value??'')} onChange={e=>{if(!draft)return;const next=structuredClone(draft);let row=next as unknown as Record<string,unknown>;for(const key of path.slice(0,-1))row=row[key] as Record<string,unknown>;if(e.target.value)row.playerId=e.target.value;else delete row.playerId;const matchPath=`${draft.dataClass==='correction'?'proposed.':''}${path.slice(-3,-1).join('.')}`;next.identityMatches=next.identityMatches.filter(m=>m.path!==matchPath);if(e.target.value)next.identityMatches.push({path:matchPath,match:{state:'confirmed',id:`public:${e.target.value}`,confirmedBy:'server'}});setDraft(next);setDirty(true);}}><option value="">Unresolved / no existing identity</option>{catalog.players.filter(p=>p.season===submission.season).map(p=><option key={p.playerId} value={p.playerId}>{p.name} — {p.schoolSlug}</option>)}</select></label>;
  if(name==='quarter')return <label key={path.join('.')}><span>Quarter</span><select aria-label="Quarter" className={style} value={String(value)} onChange={e=>edit(path,e.target.value==='OT'?'OT':Number(e.target.value))}>{['1','2','3','4','OT'].map(q=><option key={q}>{q}</option>)}</select></label>;
  if(name==='status')return <label key={path.join('.')}><span>Completeness</span><select className={style} value={String(value)} onChange={e=>edit(path,e.target.value)}>{['unknown','complete','partial','unavailable'].map(s=><option key={s}>{s}</option>)}</select></label>;
  const numeric=typeof value==='number'||['total','attempts','yards','completions','receptions','touchdowns','interceptions','firstDowns','rushingAttempts','rushingYards','passingYards','totalYards','passAttempts','interceptionsThrown','punts','puntAverage','fumbles','fumblesLost','penalties','penaltyYards'].includes(name);
  return <label className="block" key={path.join('.')}><span>{label(name)}{numeric?' (blank = unknown; 0 stays zero)':''}</span><input aria-label={label(name)} className={style} type={numeric?'number':'text'} value={String(value??'')} onChange={e=>edit(path,numeric?e.target.value===''?undefined:Number(e.target.value):e.target.value,e.target.value===''&&(numeric||['clock','note'].includes(name)))}/></label>;
 }
 const values=draft?.dataClass==='correction'?draft.values.proposed:draft?.values;
 const prefix=draft?.dataClass==='correction'?['values','proposed']:['values'];
 return <div className="space-y-5">
  <p role="status" className="whitespace-pre-wrap text-amber-200">{message}</p>
  <p>Revision {submission.revision} · {submission.state} · Approval accepts an interim export; it does not publish.</p>
  <div className="grid gap-6 lg:grid-cols-2"><aside className="space-y-4"><h2 className="text-xl font-bold">Private source evidence</h2>{submission.sources.map(source=><div key={source.id} className="border border-white/20 p-3"><h3>{source.label} · {source.state}</h3>{source.state==='finalized'&&(source.kind==='image'?<a className="underline" target="_blank" rel="noreferrer" href={`/internal/data-ingestion/${submission.id}/source/${source.id}`}>Open private sanitized image preview<Image unoptimized width={1200} height={800} alt={source.label} className="mt-3 max-h-80 max-w-full object-contain" src={`/internal/data-ingestion/${submission.id}/source/${source.id}`}/></a>:<pre className="max-h-80 overflow-auto whitespace-pre-wrap break-words text-sm">{source.body}</pre>)}<button className={button} disabled={busy||!reason} onClick={()=>run(()=>deleteSource(submission.id,submission.revision,submission.review_hash,source.id,reason))}>Delete/tombstone evidence</button></div>)}<form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);f.set('revision',String(submission.revision));f.set('hash',submission.review_hash??'');run(async()=>{const response=await fetch(`/internal/data-ingestion/${submission.id}/image`,{method:'POST',body:f});const result=await response.json();if(!response.ok)throw new Error(result.error);return result;});}}><label className="block">Evidence label<input required name="label" className={style}/></label><label className="block">Image for manual transcription<input required name="image" type="file" accept="image/jpeg,image/png,image/webp" className={style}/></label><button className={button} disabled={busy||dirty}>Retain private image</button></form></aside>
  <section className="space-y-4"><h2 className="text-xl font-bold">Typed review</h2>{draft&&submission.data_class==='game_stats'&&<label className="block">Canonical game confirmation<select className={style} aria-label="Canonical game" value={draft.target.match.state==='confirmed'?draft.target.match.id:''} disabled={submission.operation==='correct'} onChange={e=>{const next=structuredClone(draft);next.target.match=e.target.value?{state:'confirmed',id:e.target.value,confirmedBy:'server'}:{state:'unresolved',candidates:[]};if(next.dataClass==='game_stats')next.values.gameId=e.target.value||null;setDraft(next);setDirty(true);}}><option value="">Unresolved</option>{scopedGames.map(g=><option key={g.id} value={g.id}>{g.awayTeam} at {g.homeTeam} ({g.id})</option>)}</select></label>}{draft?.dataClass==='correction'&&<><p>Immutable target: {draft.target.match.id}</p><label>Correction reason<input className={style} value={draft.reason} onChange={e=>edit(['reason'],e.target.value)}/></label><details><summary>Captured baseline values</summary><pre className="overflow-auto whitespace-pre-wrap text-sm">{JSON.stringify(draft.values.current,null,2)}</pre></details></>}{values?editor(values,prefix,'values'):<p>Evidence changed; retain/revalidate a new draft before readiness.</p>}
  <button className={button} disabled={busy||!draft||submission.state==='rejected'} onClick={()=>draft&&run(()=>saveSubmission(submission.id,submission.revision,submission.review_hash,draft,crypto.randomUUID()))}>Save typed draft and validate</button>
  <h3 className="font-bold">Current validation</h3>{draft?.dataClass==='correction'&&<details><summary>Captured correction differences</summary>{submission.current?.validation.differences.map((d,i)=><div key={i} className="border-b border-white/20 py-2"><strong>{d.path||'Records'}</strong><pre className="overflow-auto whitespace-pre-wrap break-words text-sm">{JSON.stringify(d.before)} → {JSON.stringify(d.proposed)}</pre></div>)}</details>}{submission.current?.validation.blocking.map((m,i)=><p key={i} className="text-red-200">Blocker: {m}</p>)}{submission.current?.validation.warnings.map((m,i)=><p key={i} className="text-amber-100">Limitation/notice: {m}</p>)}<label className="block">Decision / warning disposition reason<input className={style} value={reason} maxLength={2000} onChange={e=>setReason(e.target.value)}/></label><div className="flex flex-wrap gap-2">{[['ready','Mark ready'],['approve','Approve interim export'],['reject','Reject'],['reopen','Reopen']].map(([command,title])=><button key={command} className={button} disabled={busy||dirty||!reason|| (command==='ready'?submission.state!=='draft':command==='approve'?submission.state!=='ready_for_review':command==='reject'?!['draft','ready_for_review'].includes(submission.state):submission.state!=='rejected')} onClick={()=>run(()=>decideSubmission(submission.id,submission.revision,submission.review_hash,command,crypto.randomUUID(),reason))}>{title}</button>)}{submission.state==='approved'&&!dirty&&<form method="post" action={`/internal/data-ingestion/${submission.id}/export`}><input type="hidden" name="revision" value={submission.revision}/><input type="hidden" name="hash" value={submission.review_hash??''}/><button className={button}>Download exact approved interim export</button></form>}</div></section></div>
 <section><h2 className="text-xl font-bold">Append-only review history</h2><a className="underline" href={`/internal/data-ingestion/${submission.id}/history`}>Browse complete history in pages</a><ol>{submission.history.map(e=><li className="border-b border-white/20 py-2" key={e.id}>{e.created_at} · {e.command} · revision {e.revision} · actor {e.actor}{e.reason?` · ${e.reason}`:''}</li>)}</ol></section>
 </div>;
}
