import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { getDistrictBySlug } from "@/lib/districts";
import { getPassingLeaders, getPlayerSeasonStats, getReceivingLeaders, getRushingLeaders } from "@/lib/player-stats";
import { getSchoolBySlug } from "@/lib/schools";
import { formatTouchdownCount } from "@/lib/stat-values";
import { getPublicCompletenessLabel, isDefinitiveRanking, type PublicCompleteness } from "@/lib/stat-completeness-public";
const SEASON=2026; type Props={params:Promise<{districtSlug:string}>}; type Row={player:string;schoolSlug:string;games:number;coverage:PublicCompleteness;values:(string|number)[]};
export async function generateMetadata({params}:Props):Promise<Metadata>{const {districtSlug}=await params;const district=getDistrictBySlug(districtSlug);return {title:district?`${district.name} 2026 Stat Leaders | VarsityVue`:"District Not Found | VarsityVue",robots:{index:false,follow:true}}}
export default async function DistrictStatsPage({params}:Props){const {districtSlug}=await params;const district=getDistrictBySlug(districtSlug);if(!district)notFound();const players=getPlayerSeasonStats(SEASON).filter((p)=>getSchoolBySlug(p.schoolSlug)?.districtId===district.id);const rushing=getRushingLeaders({season:SEASON,districtId:district.id,minAttempts:1}).slice(0,25).map((e)=>({player:e.player,schoolSlug:e.schoolSlug,games:e.gamesRecorded,coverage:e.coverage.rushing,values:[e.rushing.attempts,e.rushing.yards,formatTouchdownCount(e.rushing.touchdowns),e.rushing.yardsPerCarry]}));const passing=getPassingLeaders({season:SEASON,districtId:district.id,minAttempts:1}).slice(0,25).map((e)=>({player:e.player,schoolSlug:e.schoolSlug,games:e.gamesRecorded,coverage:e.coverage.passing,values:[`${e.passing.completions}/${e.passing.attempts}`,e.passing.yards,formatTouchdownCount(e.passing.touchdowns),e.passing.interceptions]}));const receiving=getReceivingLeaders({season:SEASON,districtId:district.id,minReceptions:1}).slice(0,25).map((e)=>({player:e.player,schoolSlug:e.schoolSlug,games:e.gamesRecorded,coverage:e.coverage.receiving,values:[e.receiving.receptions,e.receiving.yards,formatTouchdownCount(e.receiving.touchdowns),e.receiving.yardsPerReception]}));return <main className="min-h-screen bg-[#050505] text-white"><section className="border-b border-white/10 px-4 py-6 sm:px-6 sm:py-10 lg:px-8"><div className="mx-auto max-w-7xl"><Link href="/stats" className="text-[10px] font-black uppercase tracking-[0.14em] text-white/45 hover:text-white">← All Stat Leaders</Link><p className="mt-4 text-[10px] font-black uppercase tracking-[0.22em] text-[#F4EBDD]/60">2026 District View</p><h1 className="mt-2 text-3xl font-black sm:text-5xl">{district.name}</h1><p className="mt-3 max-w-3xl text-sm leading-6 text-white/55">Verified totals on file for {district.name}. Partial and unclassified values remain visible, but ordinal rank numbers are withheld whenever displayed coverage is not fully complete.</p><p className="mt-3 text-xs text-white/35">{new Set(players.map((p)=>p.schoolSlug)).size} schools · {players.length} players represented</p></div></section><section className="px-4 py-5 sm:px-6 sm:py-8 lg:px-8"><div className="mx-auto max-w-7xl space-y-5"><Board title="Rushing yards" headers={["CAR","YDS","TD","YPC"]} rows={rushing}/><Board title="Passing yards" headers={["CMP/ATT","YDS","TD","INT"]} rows={passing}/><Board title="Receiving yards" headers={["REC","YDS","TD","YPR"]} rows={receiving}/></div></section></main>}
function Board({title,headers,rows}:{title:string;headers:string[];rows:Row[]}){const definitive=isDefinitiveRanking(rows.map((r)=>r.coverage));return <section className="overflow-hidden rounded-[1.4rem] border border-white/10 bg-white/[0.045]"><div className="h-1 bg-[#8B1020]"/><div className="p-4 sm:p-6"><div className="flex items-end justify-between gap-3"><h2 className="text-2xl font-black">{title}</h2><p className="text-[9px] font-black uppercase tracking-[0.1em] text-white/30">{definitive?"Complete displayed coverage":"Verified totals · non-definitive order"}</p></div><div className="mt-4 space-y-2">{rows.map((row,index)=><div key={`${row.schoolSlug}-${row.player}`} className="grid grid-cols-[28px_minmax(0,1fr)_auto] items-center gap-3 rounded-xl border border-white/10 bg-black/30 p-3"><span className="text-center font-black text-white/30">{definitive?index+1:"•"}</span><div className="min-w-0"><p className="truncate text-sm font-black">{row.player}</p><p className="text-[10px] text-white/40">{getSchoolBySlug(row.schoolSlug)?.name??row.schoolSlug} · {row.games} G</p>{row.coverage!=="complete"&&<p className="mt-1 text-[9px] font-black uppercase text-amber-100/65">{getPublicCompletenessLabel(row.coverage)}</p>}</div><div className="flex gap-3 text-right">{headers.map((h,i)=><div key={h}><p className="text-[8px] font-black text-white/30">{h}</p><p className="text-sm font-black text-white/80">{row.values[i]}</p></div>)}</div></div>)}</div></div></section>}
